module.exports = [
    {
        date: "09.05.2020",
        words: [

            {"en": "cold feet", "ru": ["трусость"], topic: "Idioms in English - FOOT\n"},
            {"en": "get a foot in the door", "ru": ["зацепиться за возможность"], topic: "Idioms in English - FOOT\n"},
            {"en": "to put your foot in mouth", "ru": ["облажатсья сказав чуш"], topic: "Idioms in English - FOOT\n"},

            {"en": "to shoot off at the mouth", "ru": ["угрожать"], topic: "6 English idioms with the word 'mouth'\n"},
            {"en": "motor mouth", "ru": ["быстро говорить"], topic: "6 English idioms with the word 'mouth'\n"},
            {"en": "to bad mouth", "ru": ["неуважительно говорить"], topic: "6 English idioms with the word 'mouth'\n"},

            {"en": "on the dot", "ru": ["вовремя"], topic: "Idioms & Phrasal Verbs - \"on\"\n"},
            {"en": "on the go", "ru": ["в работе\n"], topic: "Idioms & Phrasal Verbs - \"on\"\n"},
            {"en": "on the hour", "ru": ["каждый час"], topic: "Idioms & Phrasal Verbs - \"on\"\n"},

            {"en": "bond", "ru": ["связь"]},

        ]
    },
    {
        date: "07.05.2020",
        words: [
            {"en": "take off", "ru": ["взлететь"], topic: "Phrasal verbs - OFF - make off, get off, pull off...\n  "},
            {"en": "make off", "ru": ["убегать"], topic: "Phrasal verbs - OFF - make off, get off, pull off...\n  "},
            {"en": "scare off", "ru": ["отпугивать"], topic: "Phrasal verbs - OFF - make off, get off, pull off...\n  "},
            {"en": "tell off", "ru": ["отчитать\n"], topic: "Phrasal verbs - OFF - make off, get off, pull off...\n  "},
            {"en": "round off", "ru": ["округлять\n"], topic: "Phrasal verbs - OFF - make off, get off, pull off...\n  "},
            {"en": "cordon off", "ru": ["оцепить"], topic: "Phrasal verbs - OFF - make off, get off, pull off...\n  "},

            {"en": "play hooky", "ru": ["отлинивать от работы"], topic: "7 Common School Expressions in English\n"},
            {"en": "cut class", "ru": ["прогуливать школу"], topic: "7 Common School Expressions in English\n"},

            {"en": "it`s touch and go", "ru": ["непредсказуемо"], topic: "6 phrases in English using IT'S\n"},
            {"en": "it`s hairy", "ru": ["страшно", "жостко"], topic: "6 phrases in English using IT'S\n"},

            {"en": "hair trigger", "ru": ["вспыльчивый\n"], topic: "English Idioms - HAIR\n"},

            {"en": "car Jack", "ru": ["угон машины"], topic: "Learn English - Talking about crime"},
            {"en": "blow away", "ru": ["завалить", "убить"], topic: "Learn English - Talking about crime"},

            {"en": "cruel", "ru": ["жестокий"], topic: ""},

            ]
    },
    {
        date: "05.05.2020",
        words: [
            {"en": "downtime", "ru": ["время простоя\n"], topic: "What do you do for fun?"},
            {"en": "spare time", "ru": ["небольшое свободное время"], topic: "What do you do for fun?"},
            {"en": "time off", "ru": ["большое свободное время"], topic: "What do you do for fun?"},
            {"en": "deal me in", "ru": ["я в игре", "я участвую"], topic: "DEAL expressions - \"big deal\", \"deal with it\"..."},
            {"en": "big deal", "ru": ["неважно"], topic: "DEAL expressions - \"big deal\", \"deal with it\"..."},
            {"en": ["zit", "pimple"], "ru": ["прыщ"], topic: "Clean yourself!!!"},
            {"en": "loss", "ru": ["потеря"], topic: "Confusing Words: MISS or LOSE?"},
            {"en": "at the drop of a hat", "ru": ["сразу же\n"], topic: "Learn 5 easy HAT idioms in English"},
            {"en": "hold on to your hat", "ru": ["держись", "крепись"], topic: "Learn 5 easy HAT idioms in English"},
            {"en": "hats off", "ru": ["снимаю шляпу\n"], topic: "Learn 5 easy HAT idioms in English"},
            {"en": "keep it under your hat", "ru": ["сохранять секрет"], topic: "Learn 5 easy HAT idioms in English"},
            {"en": "wear many hats", "ru": ["отвечать за разные задачи"], topic: "Learn 5 easy HAT idioms in English"},
            {"en": "struck", "ru": ["поражен"]},
            {"en": "hospitable", "ru": ["гостеприимный"]},
            {"en": "farewell", "ru": ["прощальный"]},
        ],
    },

    {
        date: "03.05.2020",
        words: [
            {"en": "to compete", "ru": ["соревноваться"], topic: "How to talk about sports in English"},

            {"en": "one tenth", "ru": ["одна десятая"], topic: "Как Произнести Числа на Английский"},
            {"en": "one hundredth", "ru": ["одна сотая"], topic: "Как Произнести Числа на Английский"},
            {"en": "one point eight", "ru": ["1.8"], topic: "Как Произнести Числа на Английский"},
            {"en": "one half", "ru": ["одна вторая"], topic: "Как Произнести Числа на Английский"},
            {"en": "one third", "ru": ["одна третья"], topic: "Как Произнести Числа на Английский"},
            {"en": ["one fourth", "one quarter"], "ru": ["одна четвертая"], topic: "Как Произнести Числа на Английский"},
            {"en": "one twenty first", "ru": ["одна дватать первая"], topic: "Как Произнести Числа на Английский"},

            {"en": "catch up with", "ru": ["обмениваться информацией"], topic: "English Expressions: three-word phrasal verbs"},
            {"en": "put up with", "ru": ["смириться с\n", "терпеть"], topic: "English Expressions: three-word phrasal verbs"},
            {"en": "come up with", "ru": ["придумать"], topic: "English Expressions: three-word phrasal verbs"},
            {"en": "team up with", "ru": ["объединиться с\n"], topic: "English Expressions: three-word phrasal verbs"},

            {"en": "amateur", "ru": ["любитель"]},
            {"en": "midst", "ru": ["среди"]},
            {"en": "involuntarily", "ru": ["непреднамеренно"]},
            {"en": "to intend", "ru": ["намереваться"]},
            {"en": "Gradually", "ru": ["Постепенно"]},
            {"en": "ambient", "ru": ["окружающий", "охватывающий"]},
            {"en": "neat", "ru": ["аккуратный", "опрятный"]},
            {"en": "Courtesy", "ru": ["учтивость", "вежливость"]},
            {"en": "willing", "ru": ["готовы", "добровольный"]},
            {"en": "ubiquitous", "ru": ["вездесущий", "повсеместный"]},
            {"en": "assuredly", "ru": ["конечно", "несомненно"]},
            {"en": "frontiers", "ru": ["границы"]},
        ],
    },
    {
        date: "02.05.2020",
        words: [
            {"en": "sober", "ru": ["трезвый"], topic: "Improve your social skills with Bar English!!!"},
            {"en": "it`s on me", "ru": ["я плачу"], topic: "Improve your social skills with Bar English!!!"},
            {"en": "mug", "ru": ["большая кружка"], topic: "Improve your social skills with Bar English!!!"},
            {"en": "tap", "ru": ["кран в раковене"], topic: "Improve your social skills with Bar English!!!"},
            {"en": "brew", "ru": ["напиток"], topic: "Improve your social skills with Bar English!!!"},
            {"en": "potent", "ru": ["сильнодействующий", "мощный"], topic: "Improve your social skills with Bar English!!!"},

            {"en": "awkward", "ru": ["неловко"]},

            {"en": "set up", "ru": ["установить, настроить систему", "поставить когото на место"], topic: "5 conversation phrasal verbs you need to know\n"},
            {"en": "work out", "ru": ["устранять проблему", "помериться", "удачно завершить", "заниматся спортом"], topic: "5 conversation phrasal verbs you need to know\n"},
            {"en": "turn out", "ru": ["оказаться", "выпускать какоето количество"], topic: "5 conversation phrasal verbs you need to know\n"},
            {"en": "cut off", "ru": ["обрывать", "подрезать на машине"], topic: "5 conversation phrasal verbs you need to know\n"},

            {"en": "hold up", "ru": ["подожди"]},
            {"en": "skinny", "ru": ["тощий"]},
            {"en": "svelte", "ru": ["стройный", "тощий"]},

            {"en": "rat race", "ru": ["крысиные бега\n", "бесплодная деятельность\n"], topic: "Animal idioms and expressions in English\n"},
            {"en": "pig out", "ru": ["обжираться"], topic: "Animal idioms and expressions in English\n"},
            {"en": "to hog smth", "ru": ["забирать себе слишком много"], topic: "Animal idioms and expressions in English\n"},
            {"en": "smell a rat", "ru": ["заподозрить неладное\n"], topic: "Animal idioms and expressions in English\n"},

            {"en": "pass away", "ru": ["скончаться"], topic: "How to talk about DEATH in English"},
            {"en": "rest in peace", "ru": ["Покойся с миром\n"], topic: "How to talk about DEATH in English"},
            {"en": "burial", "ru": ["захоронение"], topic: "How to talk about DEATH in English"},
            {"en": ["casket", "coffin"], "ru": ["гроб"], topic: "How to talk about DEATH in English"},
            {"en": "funeral", "ru": ["похороны"], topic: "How to talk about DEATH in English"},
            {"en": "pyre", "ru": ["погребальный костер\n"], topic: "How to talk about DEATH in English"},

            {"en": "skiing", "ru": ["катание на лыжах\n"]},
            {"en": "makeshift", "ru": ["импровизированный"]},
            {"en": "sleds", "ru": ["сани"]},
            {"en": "plank", "ru": ["доска"]},
            {"en": "plywood", "ru": ["фанера"]},
            {"en": "to strapping", "ru": ["обвязывать"]},
            {"en": "skis", "ru": ["лыжи"]},
            {"en": "bent", "ru": ["изогнутый"]},
            {"en": "outcast", "ru": ["изгой"]},
            {"en": "slope", "ru": ["наклон"]},
            {"en": "outnumber", "ru": ["большенство"]},
            {"en": "shift", "ru": ["сдвиг"]},
        ],
    },
    {
        date: "01.05.2020",
        words: [
            {"en": "we are dating", "ru": ["Мы встречаемся"], topic: "Love, Dating, and Relationships"},
            {"en": "dump", "ru": ["бросить"], topic: "Love, Dating, and Relationships"},
            {"en": "carry", "ru": ["нести"], topic: "Roots - \"port\""},
            {"en": "prick", "ru": ["член", "укол от иголки"], topic: "Slang with Christian Bale, Batman!"},
            {"en": "give a fuck", "ru": ["похуй", "неважно"], topic: "Slang with Christian Bale, Batman!"},
            {"en": "sake", "ru": ["ради"], topic: "Slang with Christian Bale, Batman!"},
        ],
    },
    {
        date: "30.04.2020",
        words: [
            {"en": "ject", "ru": ["бросать"], topic: "ject"},
            {"en": "to object", "ru": ["возражать"], topic: "ject"},
            {"en": "to interject", "ru": ["вставлять"], topic: "ject"},
            {"en": "to subject", "ru": ["подчинить"], topic: "ject"},
            {"en": "to eject", "ru": ["выбросить"], topic: "ject"},
            {"en": "to deject", "ru": ["отвергать"], topic: "ject"},
            {"en": "kitty corner", "ru": ["По диагонали"], topic: "Talking about Directions"},
            {"en": "boots", "ru": ["сапоги"], topic: "Winter Clothing"},
            {"en": "long johns", "ru": ["кальсоны"], topic: "Winter Clothing"},
            {"en": "to be layering", "ru": ["укутываться"], topic: "Winter Clothing"},
            {"en": "ruckus", "ru": ["шум гам"], topic: "NOISE"},
            {"en": "racket", "ru": ["громкий раздражающий шум"], topic: "NOISE"},
            {"en": "squabble", "ru": ["ссора из-за пустяков\n"], topic: "NOISE"},
            {"en": "commotion", "ru": ["заваруха"], topic: "NOISE"},
            {"en": "vert", "ru": ["поворачивать на латинском"], topic: "VERT words"},
            {"en": "to pervert", "ru": ["извращать"], topic: "VERT words"},
            {"en": "to divert", "ru": ["отклонять"], topic: "VERT words"},
            {"en": "pervert", "ru": ["извращенец"], topic: "VERT words"},
            {"en": "to subvert", "ru": ["разрушать"], topic: "VERT words"},
            {"en": "muse", "ru": ["муза"], topic: "MUSE words"},
            {"en": "to muse", "ru": ["размышлять", "задумываться"], topic: "MUSE words"},
            {"en": "to amuse", "ru": ["развлекать"], topic: "MUSE words"},
            {"en": "to bemuse", "ru": ["ошеломлять", "смущать"], topic: "MUSE words"},
            {"en": "thoroughly", "ru": ["тщательно"]},
        ],
    },
    {
        date: "28.04.2020",
        words: [
            {"en": "insult", "ru": ["оскорбление"],},
            {"en": "sucker", "ru": ["доверчивый лошок"],},
            {"en": "make out", "ru": ["долго ццеловаться", "слышать или видеть чтото с трудом"],},
            {"en": "screw", "ru": ["винт"], topic: "screw"},
            {"en": "screw driver", "ru": ["отвертка"], topic: "screw"},
            {"en": "screw up", "ru": ["ошибаться"], topic: "screw"},
            {"en": "to screw", "ru": ["заниматься сексом", "обманывать"], topic: "screw"},
            {"en": "to screw off", "ru": ["уходить"], topic: "screw"},
            {"en": "to be screwed", "ru": ["иметь проблемы"], topic: "screw"},
            {"en": "screw around", "ru": ["изменять"], topic: "screw"},
            {"en": "to break a 10$", "ru": ["разменять 10 долларов"], topic: "break"},
            {"en": "give me a break", "ru": ["дай мне шанс", "дай мне передохнуть"], topic: "break"},
            {"en": "to break up", "ru": ["расстоваться"], topic: "break"},
            {"en": "prejudice", "ru": ["предубеждение", "ущерб"]},
            {"en": "biased", "ru": ["предпочитающий", "необьективный"],},
        ],
    },
    {
        date: "27.04.2020",
        words: [
            {"en": "drowsy", "ru": ["сонный"],},
            {"en": "to assume", "ru": ["предполагать", "принимать", "брать на себя", "делать вид"],},
            {"en": "pretend", "ru": ["делать вид"],},
            {"en": "assumption", "ru": ["предположение"],},
            {"en": "effort", "ru": ["усилие"],},
            {"en": "to presume", "ru": ["предполагать"],},
            {"en": "to glare", "ru": ["свирепо смотреть"],},
            {"en": "scent", "ru": ["запах"],},
            {"en": "to blow some money", "ru": ["много тратить"],},
            {"en": "to blow up", "ru": ["взрывать"],},
            {"en": "nominee", "ru": ["номинант"],},
            {"en": "caucus", "ru": ["партийное собрание"],},
            {"en": "incumbent", "ru": ["избранный"],},
            {"en": "poll", "ru": ["голосование"],},
            {"en": "pundit", "ru": ["эксперт"],},
        ],
    },
]
